version: '3'

services:
  to-do-app:
    container_name: to-do-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # make sure our local doesn't override containers
    build: .
    ports:
      - '3000:3000'

  postgres:
    container_name: postgres
    image: 'postgres:12.2-alpine'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
