version: 2
jobs:
  test_and_build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
        paths:
          - .
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Running Linter
          command: npm run lint
      - run:
          name: Running Unit Tests
          command: npm run test
      - run:
          name: Running Build
          command: npm run build
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test_and_build:
    jobs:
      - test_and_build
